repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: pdm run isort
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: pdm run black
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: pdm run flake8
    types: [python]
    exclude: setup.py

  - id: refurb
    name: refurb
    stages: [commit]
    language: system
    entry: pdm run refurb
    types: [python]

  - id: pyright
    name: pyright
    stages: [commit]
    language: system
    entry: pdm run pyrigh
    types: [python]
