name: Performance

on:
  push:
    branch: [main]

jobs:
  scalene:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pdm install --no-editable --no-lock

      - name: Scalene
        run: pdm run scalene --cli --json -- norma2/__main__.py playground --only-exit-code || exit 0

  memray:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pdm install --no-editable --no-lock

      - name: memray setup
        run: pdm run memray run -o memray-norma2.bin -- norma2/__main__.py playground --only-exit-code || exit 0

      - name: Memray Stats
        run: pdm run memray stats memray-norma2.bin

      - name: Memray Summary
        run: pdm run memray summary memray-norma2.bin

      - name: Memray Tree
        run: pdm run memray tree memray-norma2.bin

  pyperf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pdm install --no-editable --no-lock

      - name: pyperf setup
        run: pdm run ./assets/scripts/pyperf_norma.py -o pyperf-norma2.json

      - name: Pyperf Show
        run: pdm run pyperf show pyperf-norma2.json

      - name: Pyperf Stats
        run: pdm run pyperf stats pyperf-norma2.json

      - name: Pyperf Slowest
        run: pdm run pyperf slowest pyperf-norma2.json
