name: Performance

on:
  push:
    branch: [main, dev]

jobs:
  scalene:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pdm install --no-editable --no-lock

      - name: Scalene
        run: pdm run scalene --cli --json -- norma2/__main__.py playground --only-exit-code || exit 0

  memray:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pdm install --no-editable --no-lock

      - name: memray setup
        run: pdm run memray run -o memray-norma2.bin -- norma2/__main__.py playground --only-exit-code || exit 0

      - name: Memray Stats
        run: pdm run memray stats memray-norma2.bin

      - name: Memray Summary
        run: pdm run memray summary memray-norma2.bin

      - name: Memray Tree
        run: pdm run memray tree memray-norma2.bin

  hyperfine:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pdm install --no-editable --no-lock

      - name: Install Hyperfine
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.15.0/hyperfine-musl_1.15.0_amd64.deb
          sudo dpkg -i ./hyperfine-musl_1.15.0_amd64.deb

      - name: Hyperfine
        run: hyperfine 'pdm run norma2 playground --only-exit-code' -i --warmup 2

